# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
# Jobs to execute when commit was pushed to repository
jobs:
  # Build package
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run: npm build .

  # Publish package
  publish:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      # Login using token
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  publish:
    jobs:
      # execute `build` all branches.
      - build:

      # execute `publish` tagged commit only. (Tag format like `v0.1.1`)
      - publish:
        filters:
          # ignore all branch because circleci defaultly will run the job for all branches if neither "only" nor "ignore" are specified.
          #   ref. https://qiita.com/sawadashota/items/ba89382d563bc90bb5cd
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
